[build]
  functions = "functions-build"
  # This will be run the site build
  command = "npm run build"
  # This is the directory is publishing to netlify's CDN
  publish = "build"
[template.environment]
  FAUNADB_SECRET = "Your FaunaDB Server Secret"
